### ISSUE TITLE
[React-rails] Navbar toggle snaps shut when using on larger screens

### ISSUE THREAD

**Issue by joshdcomp** [react-bootstrap/react-bootstrap#1814]
I want to use the navbar on all screensizes. I couldn't find an option in the navbar component documentation (so I suppose that's another ticket, but ¯\\\_(ツ)\_/¯).

I guess I should also preface by saying this is specifically happening in the port for react rails, I haven't had a chance to test in the newest version.

I started with this css snippet from this [stackoverflow ticket](http://stackoverflow.com/questions/23641125/easiest-way-to-have-a-bootstrap-layout-where-the-burger-menu-is-always-visible), which displays the hamburger just fine, but when I try to toggle the menu, it opens, then snaps shut:

![](http://i.imgur.com/mbuZoZx.gif)

Relevant css:

```css
.navbar-header {
    float: none;
  }
  .navbar-toggle {
    display: block;
  }

  .navbar-collapse.collapse {
    display: none!important;
  }
  .navbar-nav {
    float: none!important;
    margin: 7.5px -15px;
  }
  .navbar-nav>li {
    float: none;
  }
  .navbar-nav>li>a {
    padding-top: 10px;
    padding-bottom: 10px;
  }
```

Relevant code from the component here:

```jsx
var MyNavbar = React.createClass({
  getInitialState: function() {
    return {
      navExpanded: false
    };
  },
  render: function() {
    return (
      <Navbar
        inverse
        className="_navbar-primary"
        onToggle={this.handleNavToggle}
        defaultExpanded={false}
        expanded={this.state.navExpanded}
        eventKey={0.1}
      >
        <Navbar.Header>
          <Navbar.Brand>
            <Logo className="navbar-brand" />
          </Navbar.Brand>
          <Navbar.Toggle />
          {$greeting}
        </Navbar.Header>

        <Navbar.Collapse>
          {/*dropdown content*/}
        </Navbar.Collapse>
      </Navbar>
    );
  },

  handleNavToggle: function(navExpanded) {
    this.setState({
      navExpanded: navExpanded//also tried !navExpanded as well
    })
  }
});
```

Am I doing something wrong? Does the hamburger not support this functionality? Any pointers would be helpful

**Comment by taion** [comment]
The animation isn't a React-Bootstrap bit of functionality beyond toggling the overall collapsed class. You need to set up your CSS appropriately to support whatever you're trying to do here.

**Comment by joshdcomp** [comment]
@taion the classes are being added and then removed

**Comment by joshdcomp** [comment]
@taion: 

![](http://i.imgur.com/2J1mrpe.gif)

**Comment by taion** [comment]
Yes, "collapsing" is added while the animation plays. The styling for the open or closed states is controlled entirely by that `in` class.

**Comment by joshdcomp** [comment]
Ah, yeah good call. Looks like in the css snipped from the StackOverflow answer I posted, there was no modifier style for when the navbar is shown.

For posterity, here's the corrected css from that original stackoverflow (unfortunately those `!important` flags are necessary):

```css
.navbar-header {
    float: none;
  }
  .navbar-toggle {
    display: block;
  }

  .navbar-collapse.collapse {
    display: none!important;
  }

  .navbar-collapse.collapse.in {
    display: block!important;
  }
  .navbar-nav {
    float: none!important;
    margin: 7.5px -15px;
  }
  .navbar-nav>li {
    float: none;
  }
  .navbar-nav>li>a {
    padding-top: 10px;
    padding-bottom: 10px;
  }
```

**Comment by jquense** [comment]
```css
.navbar-collapse.collapse {
    display: none!important;
  }
```

is the problem, you also need a style for `in` that sets `display: block` the `!important` is rolling over the default one
