### ISSUE TITLE
The DropdownToggle should remove type="button" if the useAnchor property is set to true

### ISSUE THREAD

**Issue by cheton** [react-bootstrap/react-bootstrap#1830]
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/DropdownToggle.js#L22
https://github.com/react-bootstrap/react-bootstrap/blob/master/src/NavDropdown.js#L12

The `type="button"` property should be removed from <b>DropdownToggle</b> if the <b>useAnchor</b> property is explicitly set.

Currently, it breaks the layout in <b>NavDropdown</b> while including `normalize.css@4.1`, which built-in the following style:
```css
[type=reset], [type=submit], button, html [type=button] {
    -webkit-appearance: button
}
```
