### ISSUE TITLE
Gutter width property on Row?

### ISSUE THREAD

**Issue by olalonde** [react-bootstrap/react-bootstrap#1992]
It would be useful to be able to specify a smaller gutter width on rows. Right now, I accomplish this with the following css:

```scss
@import '~theme/common';

.small {
  $custom-grid-gutter-width: $grid-gutter-width / 2;

  margin-left: -$custom-grid-gutter-width / 2;
  margin-right: -$custom-grid-gutter-width / 2;

  :global {
    .row {
      margin-left: -$custom-grid-gutter-width / 2;
      margin-right: -$custom-grid-gutter-width / 2;
    }
  }

  [class^='col-'],
  [class*=' col-'] {
    padding-left: $custom-grid-gutter-width / 2;
    padding-right: $custom-grid-gutter-width / 2;
  }
}
```

and custom Row component:

```javascript
import React from 'react'
import { Row } from 'react-bootstrap'

import styles from './styles.scss'

export default (props) => {
  const classNames = []
  if (props.gutterSize) {
    classNames.push(styles[props.gutterSize])
  }
  if (props.className) {
    classNames.push(props.className)
  }
  return (
    <Row {...props} className={classNames.join(' ')} />
  )
}
```

usage: `<Row gutterSize="small"></Row>`
