### ISSUE TITLE
vertical center Modal

### ISSUE THREAD

**Issue by amgohan** [react-bootstrap/react-bootstrap#2118]
Hi,

I am desperately trying to vertical align my modal in my page, I didn't succeed to do that.

Can you provide a simple way (a boolean property) that can be configured to vertically center the modal

**Comment by taion** [comment]
Dupe https://github.com/react-bootstrap/react-bootstrap/issues/2038

**Comment by jquense** [comment]
so that we just have this on record

```css
. modal-dialog {
  margin-top: 50%;
  transform: translateY(-50%);
}
```

I believe works but that gets ugly when the modal overflows the page
