### ISSUE TITLE
Multiple modal, backdrop z-index

### ISSUE THREAD

**Issue by Vivekbhusal** [react-bootstrap/react-bootstrap#2135]
The z-index of all backdrop is same (1040), where, it should be above the first  or previous modal. 

Reproducible example:
https://jsfiddle.net/yrd03t24/

Also, is there a way to add class to backdrop div?

I am happy to contribute. Is there any plan to improve on this?

**Comment by jquense** [comment]
bootstrap modals are not "stackable" by design and we don't plan on adding it here. If you need that behavior try `react-bootstrap-modal`

**Comment by ammmze** [comment]
I realize this is an old thread, but I was looking for this ability and this was the first thread on the issue. I did find some styles we could apply to make them stackable though...

I had to bump the react-bootstrap version a little bit. I left the react version as-is.
https://jsfiddle.net/v8fmfmjk/4/

So the styles are: 
```css
div[data-reactroot][role="dialog"],
div[data-reactid][role="dialog"]:not(.modal) {
    position: relative;
    z-index: 1;
    height: 0;
    overflow: visible;
}
```

Though in my own scenario using a newer version of react, react-bootstrap, and bootstrap, all I needed was:

```css
div[data-reactroot][role="dialog"] {
    position: relative;
    z-index: 1;
}
```

Though with this method, the backdrop would get darker with each modal you open since the semi-transparent backdrops are still peering through to the next layer.
