### ISSUE TITLE
Question: onHide modal animation

### ISSUE THREAD

**Issue by grydstedt** [react-bootstrap/react-bootstrap#2151]
If `this.props.onHide` is called from inside a modal (instead of close button or backdrop), and the parent sets `show={false}` no fade animation is applied because modal is unmounted (I assume). Is there a recommended way to do this to keep the hide animation? Thanks

**Comment by taion** [comment]
Can you post an example of this? There shouldn't be any difference.

**Comment by bbtfr** [comment]
I met the same issue, with 2 hours' investigation, I found that if there is a css translation property on `.btn`, then no fade animation is applied.
I think it's because `react-overlays` catches `.btn`'s translation end event and destroys dom element, and the animation hasn't finished at that time.

**Comment by bbtfr** [comment]
```scss
.btn {
  @include transition(opacity .1s ease, background-color .1s ease, color .1s ease, border-color .1s ease);

  &:hover,
  &:focus {
    filter: alpha(opacity = 80);
    opacity: .8;
  }
}
```
