### ISSUE TITLE
ListGroup.Item mouseover bring item in front

### ISSUE THREAD

**Issue by davidnussio** [react-bootstrap/react-bootstrap#3447]
Hello, good job with this new beta version!

I'am starting migrating an application but I found out a problem with react-select opened menu over the ListGroup.
Because the react-select menu is hidden by listgroup item on mouse over event.

I reproduced the problem without react-select but with a simple div, check this out:
[https://codesandbox.io/s/j7pr0mxply](https://codesandbox.io/s/j7pr0mxply)

David

**Comment by davidnussio** [comment]
I'am using this workaround... but I don't understand what is the problem.

```css
.list-group {
  display: block;
}
.list-group-item {
  position: inherit;
}
```
