### ISSUE TITLE
Could I change spinner size?

### ISSUE THREAD

**Issue by dojun-hoztec** [react-bootstrap/react-bootstrap#5590]
I want to change the spinner's size

I changed size attribute 'sm' to 'md' and 'lg' but It wasn't changed and it was fixed to 'sm'

how to change the size?

**Comment by Roman1001** [comment]
You could set width and height manually:

```jsx
<Spinner animation="border" role="status" style={{ width: "25px", height: "25px" }}>
  <span className="sr-only">Loading...</span>
</Spinner>
```

or via CSS:

```scss
.spinner-border, .spinner-grow {
  width: 25px;
  height: 25px;
}
```
