### ISSUE TITLE
Is there a way to vertically align the modal ? 

### ISSUE THREAD

**Issue by Anenth** [react-bootstrap/react-bootstrap#995]
I want to vertically align the modal with respect to the window. Is it possible to do it right now ? or is it more like a feature to be added ?

**Comment by jquense** [comment]
Not without knowing some dimensions up front there isn't

if you know the height modal, you can probably right a css class that does it using [`calc`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) and the `vh` css units. Otherwise you'd need to use javascript to do it.

**Comment by Anenth** [comment]
I think adding below snippet will fix the issue.
```css
 .modal-dialog {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) !important;
    }
```
